### ISSUE TITLE
Создать макет основной страницы в Figma

### ISSUE THREAD

**Issue by Darina1801** [Telepuziki/To-do-List#11]

**Comment by DenisYakunin** [comment]
![Desktop - 1](https://github.com/Telepuziki/To-do-List/assets/138122117/bbf38161-fad7-4001-a6cd-1b30142473be)

**Comment by DenisYakunin** [comment]
Предлагаю такой вариант

**Comment by Darina1801** [comment]
Давай какие-нибудь кнопки сделаем бтрюзовыми, как лого?

**Comment by EGoncharova** [comment]
Классно ты это реализовал. Я бы не стала ничего менять. Мне так нравится

**Comment by DenisYakunin** [comment]
Сделал второй вариант с кнопками в цвет лого. Оба макета доступны по ссылке.
https://www.figma.com/file/biSsb7w4paZ6xsnvvrH7a6/layout?type=design&node-id=0%3A1&mode=design&t=rb0KUiJwVG98ThA0-1

**Comment by Darina1801** [comment]
@DenisYakunin Я имела в виду это лого: #7

**Comment by DenisYakunin** [comment]
Готово, ссылка та же

**Comment by Darina1801** [comment]
Отличная работа!
