### ISSUE TITLE
Лого организации

### ISSUE THREAD

**Issue by Darina1801** [Telepuziki/To-do-List#6]
Создать лого организации Телепузики в Figma

**Comment by DenisYakunin** [comment]
![Group 1](https://github.com/Telepuziki/To-do-List/assets/138122117/182a79f2-73fe-4c73-b6b6-0d3f9b0f3386)

**Comment by DenisYakunin** [comment]
Ожидаю ваши замечания и предложения коллеги

**Comment by Darina1801** [comment]
А можешь еще квадратное сделать лого? Центр круглый, а рамка квадратная

**Comment by DenisYakunin** [comment]
![Group 2](https://github.com/Telepuziki/To-do-List/assets/138122117/bb4257d2-a263-4978-8c2c-3f05168c74de)
![Group 3](https://github.com/Telepuziki/To-do-List/assets/138122117/99ae6beb-daa4-42f0-8f62-04a31e2645e0)

**Comment by DenisYakunin** [comment]
Либо можно закруглить текст
![Uploading Group 4.png…]()

**Comment by Darina1801** [comment]
Мне со скругленным текстом больше нравится

**Comment by DenisYakunin** [comment]
Можно обводку еще добавить 
![Group 2](https://github.com/Telepuziki/To-do-List/assets/138122117/25efe955-582b-404d-b54b-0c57c6915e34)
![Group 1](https://github.com/Telepuziki/To-do-List/assets/138122117/c1d47dce-91dc-49e3-8f47-afc57e693f2c)

**Comment by Darina1801** [comment]
Класс, спасибо!
