### ISSUE TITLE
Лого продукта

### ISSUE THREAD

**Issue by Darina1801** [Telepuziki/To-do-List#7]
Создать лого для нашего To do трекера в Figma

**Comment by RaulGasanov** [comment]
![logo](https://github.com/Telepuziki/To-do-List/assets/104073834/6ee5f2ee-b387-4aa5-b545-b0d412891dee)

Сюда не получается загрузить в формате .ico

**Comment by Darina1801** [comment]
Отлично! Теперь, когда у нас есть уже рабочая версия, давай попробуем попереставлять лист с галочка и и карандаш.
Можешь сделать их по центру? Сравним, что будет лучше

**Comment by DenisYakunin** [comment]
Мне тоже нравится
